# -*- coding: utf-8 -*-

locales = {
    'en-GB': 'Europe/London',
    'en-US': 'America/New York',
    'en-CA': 'America/New York',
    'en-AU': 'Australia/Sydney',
    'en-IN': 'Asia/Kolkata',
    'fr-FR': 'Europe/Paris',
    'fr-CA': 'America/New York',
    'de-DE': 'Europe/Berlin',
    'it-IT': 'Europe/Rome',
    'es-ES': 'Europe/Madrid',
    'es-MX': 'America/Mexico City',
    'ja-JP': 'Asia/Tokyo'
}

strings_en = {
'welcome1':"Welcome to Youtube. Say, for example, play videos by The Beatles.",
'welcome2':"Or you can say, shuffle songs by Michael Jackson.",
'help':"For example say, play videos by Fall Out Boy",
'illegal':"You can't do that with this skill.",
'gonewrong':"Sorry, something's gone wrong",
'playlist':"The playlist",
'channel':"The channel",
'video':"The video",
'notworked':"hasn't worked, shall I try the next one?",
'playing':"Playing",
'pausing':"Pausing",
'nomoreitems':"There are no more items in the playlist.",
'resuming':"Resuming",
'noresume':"I wasn't able to resume playing.",
'novideo':"I wasn't able to play a video.",
'notitle':"I can't find out the name of the current video.",
'nowplaying':"Now playing",
'nothingplaying':"Nothing is currently playing.",
'sorryskipby':"Sorry, I didn't hear how much to skip by",
'sorryskipto':"Sorry, I didn't hear where to skip to",
'ok':"OK",
'currentposition':"The current position is",
'hours':"hours",
'hour':"hour",
'minutes':"minutes",
'minute':"minute",
'seconds':"seconds",
'second':"second",
}
strings_fr = {
'welcome1':"Bienvenue sur Youtube. Dite, par exemple, jouer une vidéo de Madonna.",
'welcome2':"Ou vous pouvez dire, chanson aléatoire de Michael Jackson.",
'help':"Par exemple dite, joue une vidéo de Michael Jackson",
'illegal':"Vous ne pouvez pas faire ça avec cette skill.",
'gonewrong':"Désolé, quelque chose n'a pas fonctionné",
'playlist':"La playlist",
'channel':"La chaîne",
'video':"The vidéo",
'notworked':"ne fonctionne pas, dois je essayer la suivante ?",
'playing':"Lecture de",
'pausing':"En pause",
'nomoreitems':"Il n'y a plus rien à lire dans cette playlist.",
'resuming':"Reprise",
'noresume':"Je n'ai pas pu reprendre la lecture.",
'novideo':"Je ne peux pas lire la vidéo.",
'notitle':"Je ne retrouve pas le nom de cette vidéo.",
'nowplaying':"Vous écoutez ",
'nothingplaying':"Il n'y a aucune lecture en cours.",
'sorryskipby':"Désolé, je n'ai pas compris de combien je devais avancer ou reculer.",
'sorryskipto':"Désolé, je n'ai pas compris de combien je devais avancer ou reculer.",
'ok':"OK"
}
strings_it = {
'welcome1':"Benvenuto su YouTube. Dì, per esempio, riproduci video dei Beatles.",
'welcome2':"Oppure puoi dire, canzoni casuali di Michael Jackson.",
'help':"Per esempio dì, riproduci i video dei Fall out Boy",
'illegal':"Non puoi fare questo con questa skill.",
'gonewrong':"Spiacente, qualcosa è andato storto",
'playlist':"La playlist",
'channel':"Il canale",
'video':"Il video",
'notworked':"non ha funzionato, dovrei provare la prossima?",
'playing':"Riproduco",
'pausing':"Ciao da Youtube",
'nomoreitems':"Non ci sono più elementi nella playlist.",
'resuming':"Riprendo",
'noresume':"Non ero in grado di riprendere il video.",
'novideo':"Non ero in grado di riprodurre un video",
'notitle':"Non riesco a trovare il nome del video corrente.",
'nowplaying':"Ora riproduco",
'nothingplaying':"Al momento non sto riproducendo nulla.",
'sorryskipby':"Spiacente, non ho capito di quanto saltare",
'sorryskipto':"Spiacente, non ho capito dove saltare",
'ok':"OK"
}
strings_de = {
'welcome1':"Willkommen bei Youtube. Sagen Sie zum Beispiel, spiel Videos von The Beatles.",
'welcome2':"Oder Sie können sagen, misch Songs von Michael Jackson.",
'help':"Sie können sagen zum Beispiel, spiel Videos von Fall Out Boy ab.",
'illegal':"Sie können dies mit dieses Skill nicht tun.",
'gonewrong':"Es tut mir Leid, etwas ist schief gelaufen",
'playlist':"Die Wiedergabeliste",
'channel':"Der Kanal",
'video':"Das Video",
'notworked':"hat nicht funktioniert, soll ich das nächste versuchen?",
'playing':"Spielen",
'pausing':"Pausieren",
'nomoreitems':"Die Wiedergabeliste enthält keine weiteren Elemente.",
'resuming':"Fortfahren",
'noresume':"Ich konnte nicht weiter spielen.",
'novideo':"Ich konnte dieses Video nicht abspielen.",
'notitle':"Ich kann den Namen des aktuellen Videos nicht herausfinden.",
'nowplaying':"Jetzt spielt",
'nothingplaying':"Es wird momentan nichts abgespielt.",
'sorryskipby':"Entschuldigung, ich habe nicht gehört, wie viel ich überspringen soll",
'sorryskipto':"Entschuldigung, ich habe nicht gehört, wo ich überspringen soll",
'ok':"OK"
}
strings_es = {
'welcome1':"Bienvenido a Youtube. Di, por ejemplo, pon videos de los Beatles.",
'welcome2':"O puedes decir, aleatorio canciones de Michael Jackson.",
'help':"por ejemplo di, pon videos de Fall Out Boy",
'illegal':"Tu no puedes hacer esto con esta skill .",
'gonewrong':"Lo sentimos, ocurrio un error",
'playlist':"la playlist",
'channel':"el canal",
'video':"el video",
'notworked':"no ha funcionado desea la siguiente?",
'playing':"sonando",
'pausing':"para",
'nomoreitems':"No hay items en la playlist",
'resuming':"resumiendo",
'noresume':"No hay resumen del video",
'novideo':"No se puede reproducir el video",
'notitle':"No puedo encontrar el titulo del video",
'nowplaying':"ahora sonando",
'nothingplaying':"Nada esta sonando",
'sorryskipby':"Lo siento no escuche cuando adelantar",
'sorryskipto':"Lo siento no escuche a donde adelantar",
'ok':"OK"
}
strings_ja = {
'welcome1':"ユーチューブへようこそ.  例えば, ｢ビートルズのビデオを再生｣ と話しかけてください.",
'welcome2':"それとも, ｢マイケル・ジャクソンの曲をシャッフル再生｣ と話しかけてください.",
'help':"例えば, マイケル・ジャクソンの曲をシャッフル再生と話しかけてください.",
'illegal':"このスキルはその動作に対応しておりません.",
'gonewrong':"すいません, なにか問題が起きたようです.",
'playlist':"プレイリスト",
'channel':"チャンネル",
'video':"動画",
'notworked':"は正常に動作しませんでした. 次を試しますか?",
'playing':"再生中",
'pausing':"停止中",
'nomoreitems':"プレイリストにこれ以上動画はありません.",
'resuming':"再開中",
'noresume':"再生を再開できませんでした.",
'novideo':"動画を再生できませんでした.",
'notitle':"現在再生中の動画の名前はわかりませんでした.",
'nowplaying':"再生中",
'nothingplaying':"現在何も流れていません.",
'sorryskipby':"すいません. どれだけスキップするか聞き取れませんでした.",
'sorryskipto':"すいません. どこまでスキップするか聞き取れませんでした.",
'ok':"はい.",
'currentposition':"現在の再生位置は,",
'hours':"時間",
'hour':"時間",
'minutes':"分",
'minute':"分",
'seconds':"秒",
'second':"秒",
}
